import sys
from collections.abc import Mapping
from typing import Any, Literal, TypeAlias, overload

if sys.version_info < (3, 11):
    from typing_extensions import Self
else:
    from typing import Self

# The Any trick
# https://typing.python.org/en/latest/guides/writing_stubs.html#the-any-trick
MaybeNone: TypeAlias = Any

class PatternError(Exception): ...

class Match:
    def span(self, group: int | str = 0, /) -> tuple[int, int]: ...
    @overload
    def group(self, group: Literal[0] = 0, /) -> str: ...
    @overload
    def group(self, group: str | int, /) -> str | MaybeNone: ...
    @overload
    def group(
        self, group1: str | int, group2: str | int, /, *groups: str | int
    ) -> tuple[str | MaybeNone, ...]: ...
    @property
    def string(self) -> str: ...
    @property
    def re(self) -> Pattern: ...
    @property
    def pos(self) -> int: ...
    @property
    def endpos(self) -> int: ...
    def start(self, group: int | str = 0, /) -> int: ...
    def end(self, group: int | str = 0, /) -> int: ...
    def expand(self, template: str) -> str: ...
    def _next(self) -> Match | None: ...
    def __getitem__(self, item: int | str) -> str: ...

class Pattern:
    def __new__(cls, pattern: str, flags: int) -> Self: ...
    @property
    def pattern(self) -> str: ...
    @property
    def flags(self) -> int: ...
    @property
    def groups(self) -> int: ...
    @property
    def groupindex(self) -> Mapping[str, int]: ...
    def search(self, string: str, pos: int, endpos: int) -> Match | None: ...
    def test(self, string: str, pos: int, endpos: int) -> bool: ...

IGNORECASE: int
MULTILINE: int
DOTALL: int
UNICODE: int
STICKY: int
NAMED_GROUPS: int
UNICODE_SETS: int
